# A simple publishing platform powered by Supranim,
# a modern web framework for Nim.
#
# (c) 2026 George Lemon | AGPLv3 License
#     Made by Humans from OpenPeeps
#     https://github.com/openpeeps/sunday

import std/[os, tables]

import pkg/supranim/application
import pkg/supranim/core/services
import pkg/ozark/model
import pkg/threading/once

import pkg/[pluginkit, libevent/bindings/threaded]
export pluginkit

## This service provides a pluggable architecture for the
## application, allowing developers to create and register
## plugins that can extend the functionality of the app.
## 
## It uses the `pluginkit` package to manage plugins and
## their lifecycle.

initService SundayPluginManager[Singleton]:
  ## A singleton of `PluginManager` from the `pluginkit` package.
  backend do:
    type
      SundayPluginManager* = ref object        
        manager*: PluginManager
          ## The `PluginManager` instance part of the pluginkit package
        onInstall*: OrderedTableRef[NanoID, RuntimeSchemas]
        onUninstallAliases*: TableRef[string, NanoID]
          ## A table mapping table name to plugin ID for
          ## uninstalling tables during plugin uninstallation
          ## based on the collected schemas in the `onInstall` table
        
  client do:
    # Plugin manager callbacks for plugin load, unload, and error events
    proc onPluginLoaded(plugin: Plugin) =
      # All Sunday plugins must provide a serialized schema for database
      # models, controllers, and other components that they define (if any).
      #
      # The `onLoad` callback runs at application startup after the plugin
      # is loaded. This is where we can parse the plugin's schema, validate it
      # and register any components defined in the plugin with the application.
      let runtimeSchema = unserializeSchemas(plugin.getSchemas())
      if runtimeSchema != nil:
        # collect the plugin's schema in the `onInstall` table for execution
        # during the installation process.
        let sundayInstance = getSundayPluginManagerInstance()
        sundayInstance.onInstall[plugin.getId()] = runtimeSchema

    proc onPluginUnloaded(plugin: Plugin) =
      discard

    proc onPluginError(plugin: Plugin, error: string) =
      discard

    proc onPluginInstall*(plugin: Plugin) =
      ## This callback is not part of the pluginkit package, instead it is a 
      ## custom callback defined at the Sunday application level to handle
      ## plugin installation events triggered from the dashboard UI via control handlers.

    proc pluginManager*: ptr SundayPluginManager {.inline.} =
      ## Returns the Singleton instance of the SundayPluginManager
      getSundayPluginManagerInstance(
        proc(instance: ptr SundayPluginManager) =
          {.gcsafe.}:
            new(instance[])
            # set the callbacks for plugin events when the instance is created
            instance[].onInstall = newOrderedTable[NanoID, RuntimeSchemas]()
            instance[].onUninstallAliases = newTable[string, NanoID]()
            instance[].manager = PluginManager(callbacks:
              PluginManagerCallbacks(
                onLoad: onPluginLoaded,
                onUnload: onPluginUnloaded,
                onError: onPluginError
              )
            )
      ) # auto generated by the service manager

    const pluginsDir = "plugins"
    const pluginExt =
      when defined(windows): ".dll"
      elif defined(macosx): ".dylib"
      else: ".so" # default to .so for Linux and other Unix-like systems
      
    proc init*(app: Application) =
      ## Initialize an instance of the PluginManager when the
      ## service is initialized. This will allow plugins to be
      ## loaded and managed throughout the application.
      let pluginsPath = app.paths().getInstallationPath / pluginsDir
      
      # the current directory is always the root of the Booyaka project,
      # so we can use it to construct the path to the plugins directory 
      discard existsOrCreateDir(pluginsPath)
      for path in walkFiles(pluginsPath / "*"):
        if path.splitFile.ext == pluginExt:
          let pluginId = pluginManager().manager.load(path)