# A simple publishing platform powered by Supranim,
# a modern web framework for Nim.
#
# (c) 2026 George Lemon | AGPLv3 License
#     Made by Humans from OpenPeeps
#     https://github.com/openpeeps/sunday

import std/os

import pkg/supranim/application
import pkg/supranim/core/services
import pkg/[pluginkit, libevent/bindings/threaded]
export pluginkit

## This service provides a pluggable architecture for the
## application, allowing developers to create and register
## plugins that can extend the functionality of the app.
## 
## It uses the `pluginkit` package to manage plugins and
## their lifecycle.

initService PluginManager[Singleton]:
  ## A singleton of `PluginManager` from the `pluginkit` package.
  client do:
    # Plugin manager callbacks for plugin load, unload, and error events
    proc onPluginLoaded(plugin: Plugin) =
      echo plugin.getId()
      echo "Plugin loaded: ", plugin.getName, " by ", plugin.getAuthor

    proc onPluginUnloaded(plugin: Plugin) =
      echo "Plugin unloaded: ", plugin.getName

    proc onPluginError(plugin: Plugin, error: string) =
      echo "Error in plugin ", plugin.getName, ": ", error

    proc pluginManager*: ptr PluginManager {.inline.} =
      ## Returns the Singleton instance of the PluginManager
      getPluginManagerInstance(
        proc(instance: ptr PluginManager) =
          {.gcsafe.}:
            new(instance[])
            # set the callbacks for plugin events when the instance is created
            instance[].callbacks = PluginManagerCallbacks(
              onLoad: onPluginLoaded,
              onUnload: onPluginUnloaded,
              onError: onPluginError
            )
      ) # auto generated by the service manager

    const pluginsDir = "plugins"
    const pluginExt =
      when defined(windows): ".dll"
      elif defined(macosx): ".dylib"
      else: ".so" # default to .so for Linux and other Unix-like systems
      
    proc init*(app: Application) =
      # Initialize an instance of the PluginManager when the
      # service is initialized. This will allow plugins to be
      # loaded and managed throughout the application.
      let pluginsPath = app.paths().getInstallationPath / pluginsDir
      # the current directory is always the root of the Booyaka project,
      # so we can use it to construct the path to the plugins directory 
      discard existsOrCreateDir(pluginsPath)
      for path in walkFiles(pluginsPath / "*"):
        if path.splitFile.ext == pluginExt:
          let pluginId = pluginManager().load(path)
          echo "Loaded plugin: ", path, " with ID: ", pluginId